name: periodic healthcheck
on: [push]
    
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check the deployed service health
        uses: jtalk/url-health-check-action@v2
        with:
         url: https://${{ secrets.HEROKU_APP_NAME }}.herokuapp.com/health