name: Testing stuff

on:
  push:
    branches:
      - master

jobs:
  a_test_job:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: commit messages
        env:
          SKIP_DEPLOY: ${{ contains(join(github.event.commits.*.message, ''), '#skip') }}
        run: echo "Skip deploy? $SKIP_DEPLOY"