name: Testing stuff

on:
  push:
    branches:
      - master

jobs:
  a_test_job:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: contains false check
        env:
          SKIP_DEPLOY: |
           ${{ github.event_name == 'push' 
            && !contains(join(github.event.commits.*.message, '')) }}
        run: echo "Skip deploy? $SKIP_DEPLOY"